ApiMvcTest/Models/ErrorViewModel.cs
namespace ApiMvcTest.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ApiMvcTest/Models/Pokemon.cs
using System;
using ApiMvcTest.Data;
using Type = ApiMvcTest.Data.Type;

namespace ApiMvcTest.Models
{
    public class Pokemon
    {
        public List<string> abilities { get; set; }
        public int base_experience { get; set; }
        public int height { get; set; }
        public List<object> held_items { get; set; }
        public int id { get; set; }
        public string? location_area_encounters { get; set; }
        public List<string> moves { get; set; }
        public string? name { get; set; }
        public int order { get; set; }
        public List<object> past_types { get; set; }
        public string sprite { get; set; }
        public List<int> stats { get; set; }
        public List<string>? types { get; set; }
        public int weight { get; set; }
    }
}

ApiMvcTest/Models/Pokemons.cs
using System;
namespace ApiMvcTest.Models
{
    public class Pokemons
    {
        public static List<Pokemon> PokeList = new List<Pokemon>();

        public static void AddToList(Pokemon pokemon)
        {
            PokeList.Add(pokemon);
        }

    }
}

ApiMvcTest/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ApiMvcTest.Models;

namespace ApiMvcTest.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ApiMvcTest/Controllers/PokemonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApiMvcTest.Data;
using ApiMvcTest.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ApiMvcTest.Controllers
{
    public class PokemonController : Controller
    {
        private readonly IPokemonApiResponse _response;

        public PokemonController(IPokemonApiResponse response)
        {
            _response = response;
        }

        public IActionResult SearchForPokemon()
        {

            return View();
        }

        public IActionResult Index()
        {
            var searchString = Request.Form["searchString"];
            var myPokemon = _response.GetPokemon(searchString);
            Pokemons.AddToList(myPokemon);
            return View(myPokemon);

        }

        public IActionResult DisplayAllPokemon()
        {
            return View();
        }

    }


}

ApiMvcTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .header {
        font-family: "Press Start 2P";
        text-align: center;
    }

    p {
        font-size: 25px;
    }
</style>

<div class="header bg-dark border border-danger rounded mt-5 shadow-lg rounded">
    <h1 class="display-1 mt-4 text-warning">Pokedex</h1>
    <hr class="text-danger" />
    <p class="text-danger">Search For your Favorite Pokemon</p>
</div>

ApiMvcTest/Views/Pokemon/DisplayAllPokemon.cshtml
@model Pokemons
<style>
    .card-header {
        font-family: "Press Start 2P";
        font-size: 20px;
        text-align: center;
    }

    h5 {
        font-family: "Press Start 2P";
        font-size: 10px;
        font-weight: bold;
    }

    .header {
        font-family: "Press Start 2P";
        text-align: center;
    }

    .test-class {
        font-size: 25px;
    }

    img {
        height: 300px;
        width: auto;
    }

    .card:hover {
        animation: bounce 0.5s linear;
    }
</style>

<div class="header bg-dark border border-danger rounded mt-5 shadow-lg rounded">
    <hr />
    <h1 class="test-class display-1 mt-4 text-warning">Favorite Pokemon</h1>
    <hr />
</div>

<div class="d-flex flex-wrap justify-content-around align-content-around ">
    @foreach (var Model in Pokemons.PokeList)
    {

        <div class="card bg bg-light border-danger mb-3 mt-5 rounded shadow-lg" style="max-width: 25rem;">
            <div class="card-header">Number: @Model.id</div>
            <div class="card-body">
                <div class="d-flex align-items-center justify-content-between">
                    <h5 class="card-title text-danger">Name: <span class="text-dark">@char.ToUpper(Model.name[0])@Model.name.Substring(1)</span></h5>
                    <h5 class=" text-danger">Experience: <span class="text-dark">@Model.base_experience</span></h5>
                </div>
                <div class="d-flex align-items-center justify-content-between">
                    <h5 class="text-danger">
                        Height: <span class="text-dark">@Model.height<span>ft</span></span>
                    </h5>
                    <h5 class="text-danger">Weight: <span class="text-dark">@Model.weight<span>lbs</span></span></h5>
                </div>

                <img src="@Model.sprite" class="card-img-top border-warning rounded shadow" alt="..." />
                <p class="card-text">
                    <div class="d-flex">
                        <h5 class="text-danger">Type:&nbsp;</h5>
                        <div class="d-inline-flex">
                            @foreach (var type in Model.types)
                            {
                                <h5>@char.ToUpper(@type[0])@type.Substring(1).&nbsp;</h5>
                            }
                        </div>

                    </div>

                    <div class="d-flex">
                        <h5 class="text-danger">Abilities:&nbsp;</h5>
                        <div class="d-inline-flex">
                            @foreach (var ability in Model.abilities.Take(2))
                            {
                                <h5>@char.ToUpper(@ability[0])@ability.Substring(1).&nbsp;</h5>
                            }
                        </div>
                    </div>

                    <div class="d-flex">
                        <h5 class="text-danger">Moves:&nbsp;</h5>
                        <div class="d-inline-flex">
                            @foreach (var move in Model.moves.Take(2))
                            {
                                <h5>@char.ToUpper(@move[0])@move.Substring(1).&nbsp;</h5>
                            }
                        </div>
                    </div>
                </p>

            </div>
        </div>

    }
</div>

ApiMvcTest/Views/Pokemon/Index.cshtml
@model Pokemon
<style>
    .card-header {
        font-family: "Press Start 2P";
        font-size: 20px;
        text-align: center;
    }

    h5 {
        font-family: "Press Start 2P";
        font-size: 10px;
        font-weight: bold;
    }

    .form-poke {
        font-family: "Press Start 2P";
    }

    img {
        height: 300px;
        width: auto;
    }
</style>

<div class="form-poke container justify-content-center bg bg-dark p-3 mt-5 border border-danger rounded border shadow-lg">

    <form asp-controller="Pokemon" asp-action="Index">

        <input class="form-control" name="searchString" placeholder="Enter Pokemon Name" />
        <button class="btn btn-warning mt-3" id="submit" name="submit" type="submit" style="font-weight:bold;" value="Search">Search</button>
    </form>

</div>
<div class="d-flex justify-content-center">
    <div class="card bg bg-light border-danger mb-3 mt-5 rounded shadow-lg" style="max-width: 25rem;">
        <div class="card-header">Number: @Model.id</div>
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between">
                <h5 class="card-title text-danger">Name: <span class="text-dark">@char.ToUpper(Model.name[0])@Model.name.Substring(1)</span></h5>
                <h5 class=" text-danger">Experience: <span class="text-dark">@Model.base_experience</span></h5>
            </div>
            <div class="d-flex align-items-center justify-content-between">
                <h5 class="text-danger">
                    Height: <span class="text-dark">@Model.height<span>ft</span></span>
                </h5>
                <h5 class="text-danger">Weight: <span class="text-dark">@Model.weight<span>lbs</span></span></h5>
            </div>

            <img src="@Model.sprite" class="card-img-top border-warning rounded shadow" alt="..." />
            <p class="card-text">
                <div class="d-flex">
                    <h5 class="text-danger">Type:&nbsp;</h5>
                    <div class="d-inline-flex">
                        @foreach (var type in Model.types)
                        {
                            <h5>@char.ToUpper(@type[0])@type.Substring(1).&nbsp;</h5>
                        }
                    </div>

                </div>

                <div class="d-flex">
                    <h5 class="text-danger">Abilities:&nbsp;</h5>
                    <div class="d-inline-flex">
                        @foreach (var ability in Model.abilities.Take(2))
                        {
                            <h5>@char.ToUpper(@ability[0])@ability.Substring(1).&nbsp;</h5>
                        }
                    </div>
                </div>

                <div class="d-flex">
                    <h5 class="text-danger">Moves:&nbsp;</h5>
                    <div class="d-inline-flex">
                        @foreach (var move in Model.moves.Take(2))
                        {
                            <h5>@char.ToUpper(@move[0])@move.Substring(1).&nbsp;</h5>
                        }
                    </div>
                </div>
            </p>

        </div>
    </div>
</div>

ApiMvcTest/Views/Pokemon/SearchForPokemon.cshtml
@model Pokemon
    <style>
        .card-header {
            font-family: "Press Start 2P";
            font-size: 20px;
            text-align: center;
        }

        h5 {
            font-family: "Press Start 2P";
            font-size: 10px;
            font-weight: bold;
        }

        .form-poke {
            font-family: "Press Start 2P";
        }
    </style>

    <div class="form-poke container justify-content-center bg bg-dark p-3 mt-5 border border-danger rounded border shadow-lg">

        <form asp-controller="Pokemon" asp-action="Index">

            <input class="form-control" name="searchString" placeholder="Enter Pokemon Name" />
            <button class="btn btn-warning mt-3" id="submit" name="submit" type="submit" style="font-weight:bold;" value="Search">Search</button>
        </form>

    </div>

ApiMvcTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApiMvcTest</title>
    <!--Bootswatch-->
    <!--<link rel="stylesheet" href="~/css/bootswatch.css" />-->
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApiMvcTest.styles.css" asp-append-version="true" />
    <!-- Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap"
          rel="stylesheet" />
    <style>
        body {
            background-image: url("https://images3.alphacoders.com/273/273289.jpg");
            background-size: cover;
            background-position: center;
        }

        nav {
            font-family: "Press Start 2P";
            font-size: 15px;
        }
    </style>
</head>
<body class="bg bg-warning">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-danger border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="nav-image" style="height: 45px; width: 45px;"
                         src="https://icons-for-free.com/iconfiles/png/512/pikachu-1320568181523508516.png"
                         alt="" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pokemon" asp-action="SearchForPokemon">>Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pokemon" asp-action="DisplayAllPokemon">>List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>